/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 CP3
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Pulse.h"
#include "Pulse_aliases.h"
#include "PWM.h"
#include "Clock.h"
#include "isr_Timed.h"
#include "CLK_20Hz.h"
#include "ADC.h"
#include "PinRPM.h"
#include "PinRPM_aliases.h"
#include "EnablePWM.h"
#include "Pin_LED_G.h"
#include "Pin_LED_G_aliases.h"
#include "Pin_LED_R.h"
#include "Pin_LED_R_aliases.h"
#include "LED_G.h"
#include "LED_R.h"
#include "ADC_IRQ.h"
#include "ADC_intClock.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyLFClk.h"

/*[]*/

